# IMAGEN BASE
FROM node:18-alpine
# DIRECTORIO DE TRABAJO DENTRO DEL CONTENEDOR
WORKDIR /src
# COPIAMOS EL PACKAGE.JSON
COPY package.json  package-lock.json* ./
# INSTALAMOS LAS DEPENDENCIAS
RUN npm install
# COPIAMOS EL RESTO DE LOS ARCHIVOS
COPY . .
# EXPONEMOS EL PUERTO DE NUESTRA APP
EXPOSE 8080
# COMANDOS PARA EJECUTAR LA APP
CMD ["node", "src/app.js"]
